version: '3'
services:

  #REDIS
  redis:
    image: redis:latest
    command: redis-server --requirepass secrets
    ports:
      - "6379:6379"
      -
  #POSTGRES
  postgres:
    image: postgres:latest
    environment:
      POSTGRES_DB: secrets
      POSTGRES_USER: secrets
      POSTGRES_PASSWORD: secrets
      PGDATA: /data/postgres
    volumes:
      - ./volumes/pgdata:/data/postgres
    ports:
      - "5432:5432"
    restart: unless-stopped
